stages:
  ingest:
    cmd: python ingest.py
    deps:
      - ingest.py
    params:
      - api.latitude
      - api.longitude
      - api.start_date
      - api.end_date
      - api.variables
      - paths.raw
    outs:
      - data/raw/weather.csv

  preprocess:
    cmd: python preprocess.py
    deps:
      - preprocess.py
      - data/raw/weather.csv
    params:
      - paths.raw
      - paths.processed
    outs:
      - data/processed/weather_clean.csv
