#TODO write the Dockerfile

#TODO Define the base image (Python 3.12 image)

#TODO Set the working directory in the container

#TODO Copy the requirements.txt file to the container and install dependencies

#TODO Copy the rest of the application code to the container

#TODO Set environment variables for MLflow tracking URI, model name and model alias


#TODO Expose the port that the FastAPI app will run on

#TODO Define the command to run the FastAPI app using uvicorn
# Note: In the workspace, add --root-path /proxy/8000 to the uvicorn command
# so FastAPI can correctly generate URLs when served behind the workspace proxy.
